"""initial schema

Revision ID: 56eda77ed310
Revises: 
Create Date: 2026-06-18 13:22:32.170882
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '56eda77ed310'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('topic', sa.Enum('ALL', 'DEPARTMENT', 'SPORT', 'FIXTURE', 'URGENT_ONLY', name='notificationtopic', native_enum=False), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_events'))
    )
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.create_index('ix_notification_events_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_events_target_id'), ['target_id'], unique=False)

    op.create_table('notification_templates',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates'))
    )
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_templates_key'), ['key'], unique=True)

    op.create_table('push_subscriptions',
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_is_active'), ['is_active'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'TOURNAMENT_ADMIN', 'SCORE_OFFICIAL', 'CONTENT_MANAGER', name='rolename', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('tournaments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('public_brand', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('medal_points', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments')),
    sa.UniqueConstraint('slug', name=op.f('uq_tournaments_slug'))
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_is_current'), ['is_current'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_dev_account', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=254), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_logs_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('departments',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('abbreviation', sa.String(length=16), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('secondary_color', sa.String(length=9), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_departments_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('tournament_id', 'abbreviation', name=op.f('uq_departments_tournament_id'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_abbreviation'), ['abbreviation'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['notification_events.id'], name=op.f('fk_notification_deliveries_event_id_notification_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['push_subscriptions.id'], name=op.f('fk_notification_deliveries_subscription_id_push_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('event_id', 'subscription_id', name=op.f('uq_notification_deliveries_event_id'))
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.Enum('ALL', 'DEPARTMENT', 'SPORT', 'FIXTURE', 'URGENT_ONLY', name='notificationtopic', native_enum=False), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['push_subscriptions.id'], name=op.f('fk_notification_preferences_subscription_id_push_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('subscription_id', 'topic', 'target_id', name=op.f('uq_notification_preferences_subscription_id'))
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_subscription_id'), ['subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_preferences_target_id'), ['target_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('sponsors',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('tier', sa.String(length=40), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_sponsors_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sponsors'))
    )
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sponsors_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('sports',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gender_category', sa.Enum('MALE', 'FEMALE', 'MIXED', 'OPEN', name='gendercategory', native_enum=False), nullable=False),
    sa.Column('competition_format', sa.Enum('ROUND_ROBIN', 'GROUP_STAGE', 'KNOCKOUT', 'GROUP_THEN_KNOCKOUT', 'DIRECT_FINAL', 'RANKED_TIMED', 'INDIVIDUAL_BRACKET', 'CUSTOM', name='competitionformat', native_enum=False), nullable=False),
    sa.Column('scoring_type', sa.Enum('GOAL_BASED', 'POINT_BASED', 'SET_BASED', 'TIMED_RACE', 'RANKED_FINISH', 'BEST_OF_N', 'WIN_LOSS', 'CUSTOM_NUMERIC', name='scoringtype', native_enum=False), nullable=False),
    sa.Column('participant_kind', sa.Enum('TEAM', 'INDIVIDUAL', name='participantkind', native_enum=False), nullable=False),
    sa.Column('requires_table', sa.Boolean(), nullable=False),
    sa.Column('requires_bracket', sa.Boolean(), nullable=False),
    sa.Column('supports_live', sa.Boolean(), nullable=False),
    sa.Column('uses_timing', sa.Boolean(), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_sports_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sports')),
    sa.UniqueConstraint('tournament_id', 'slug', name=op.f('uq_sports_tournament_id'))
    )
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sports_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_sports_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_sports_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_uploaded_files_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('venues',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_venues_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('brackets',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_brackets_sport_id_sports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brackets'))
    )
    with op.batch_alter_table('brackets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brackets_sport_id'), ['sport_id'], unique=False)

    op.create_table('competition_stages',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_competition_stages_sport_id_sports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_stages'))
    )
    with op.batch_alter_table('competition_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competition_stages_sport_id'), ['sport_id'], unique=False)

    op.create_table('department_points',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('silver', sa.Integer(), nullable=False),
    sa.Column('bronze', sa.Integer(), nullable=False),
    sa.Column('participation_points', sa.Float(), nullable=False),
    sa.Column('bonus_points', sa.Float(), nullable=False),
    sa.Column('penalties', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_points_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_department_points_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_points')),
    sa.UniqueConstraint('tournament_id', 'department_id', name=op.f('uq_department_points_tournament_id'))
    )
    with op.batch_alter_table('department_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_points_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_points_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('medals',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('GOLD', 'SILVER', 'BRONZE', name='medalkind', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_medals_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_medals_sport_id_sports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_medals_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medals'))
    )
    with op.batch_alter_table('medals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medals_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medals_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('participants',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('bib_number', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_participants_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_participants_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participants'))
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participants_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('sport_rules',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('points_win', sa.Integer(), nullable=False),
    sa.Column('points_draw', sa.Integer(), nullable=False),
    sa.Column('points_loss', sa.Integer(), nullable=False),
    sa.Column('tie_breakers', sa.JSON(), nullable=False),
    sa.Column('sets_to_win', sa.Integer(), nullable=True),
    sa.Column('table_columns', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_sport_rules_sport_id_sports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sport_rules')),
    sa.UniqueConstraint('sport_id', name=op.f('uq_sport_rules_sport_id'))
    )
    op.create_table('teams',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_teams_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_teams_sport_id_sports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_teams_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('sport_id', 'department_id', name=op.f('uq_teams_sport_id'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_sport_id'), ['sport_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('groups',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_groups_sport_id_sports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['competition_stages.id'], name=op.f('fk_groups_stage_id_competition_stages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_sport_id'), ['sport_id'], unique=False)

    op.create_table('team_members',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_team_members_participant_id_participants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'participant_id', name=op.f('uq_team_members_team_id'))
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)

    op.create_table('fixtures',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('home_team_id', sa.Uuid(), nullable=True),
    sa.Column('away_team_id', sa.Uuid(), nullable=True),
    sa.Column('venue_id', sa.Uuid(), nullable=True),
    sa.Column('score_official_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'WARMUP', 'LIVE', 'HALF_TIME', 'PERIOD_BREAK', 'PAUSED', 'DELAYED', 'POSTPONED', 'COMPLETED', 'CANCELLED', 'WALKOVER', 'UNDER_REVIEW', name='fixturestatus', native_enum=False), nullable=False),
    sa.Column('round_name', sa.String(length=80), nullable=True),
    sa.Column('match_day', sa.Integer(), nullable=True),
    sa.Column('bracket_position', sa.String(length=40), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_fixtures_away_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_fixtures_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_fixtures_home_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['score_official_id'], ['users.id'], name=op.f('fk_fixtures_score_official_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_fixtures_sport_id_sports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['competition_stages.id'], name=op.f('fk_fixtures_stage_id_competition_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_fixtures_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_fixtures_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixtures'))
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_scheduled_start'), ['scheduled_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_score_official_id'), ['score_official_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_sport_id'), ['sport_id'], unique=False)
        batch_op.create_index('ix_fixtures_sport_status', ['sport_id', 'status'], unique=False)
        batch_op.create_index('ix_fixtures_start_status', ['scheduled_start', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('group_members',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_group_members_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'team_id', name=op.f('uq_group_members_group_id'))
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_team_id'), ['team_id'], unique=False)

    op.create_table('standings',
    sa.Column('sport_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_standings_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_standings_sport_id_sports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standings')),
    sa.UniqueConstraint('sport_id', 'group_id', name=op.f('uq_standings_sport_id'))
    )
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standings_sport_id'), ['sport_id'], unique=False)

    op.create_table('announcements',
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('GENERAL', 'URGENT', 'VENUE_CHANGE', 'POSTPONEMENT', 'SCHEDULE_CHANGE', 'WEATHER', 'RESULT_CORRECTION', name='announcementtype', native_enum=False), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('sport_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('fixture_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_announcements_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_announcements_department_id_departments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_announcements_fixture_id_fixtures'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_announcements_sport_id_sports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_announcements_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index('ix_announcements_published', ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('bracket_nodes',
    sa.Column('bracket_id', sa.Uuid(), nullable=False),
    sa.Column('fixture_id', sa.Uuid(), nullable=True),
    sa.Column('round_name', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('home_source', sa.String(length=80), nullable=True),
    sa.Column('away_source', sa.String(length=80), nullable=True),
    sa.Column('feeds_into_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['brackets.id'], name=op.f('fk_bracket_nodes_bracket_id_brackets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feeds_into_id'], ['bracket_nodes.id'], name=op.f('fk_bracket_nodes_feeds_into_id_bracket_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_bracket_nodes_fixture_id_fixtures'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bracket_nodes'))
    )
    with op.batch_alter_table('bracket_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bracket_nodes_bracket_id'), ['bracket_id'], unique=False)

    op.create_table('fixture_participants',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('participant_id', sa.Uuid(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_fixture_participants_fixture_id_fixtures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_fixture_participants_participant_id_participants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_fixture_participants_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixture_participants'))
    )
    with op.batch_alter_table('fixture_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixture_participants_fixture_id'), ['fixture_id'], unique=False)

    op.create_table('live_match_states',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('current_period_number', sa.Integer(), nullable=False),
    sa.Column('clock_text', sa.String(length=20), nullable=True),
    sa.Column('home_sets', sa.Integer(), nullable=False),
    sa.Column('away_sets', sa.Integer(), nullable=False),
    sa.Column('status_text', sa.String(length=80), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_live_match_states_fixture_id_fixtures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_live_match_states'))
    )
    with op.batch_alter_table('live_match_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_match_states_fixture_id'), ['fixture_id'], unique=True)

    op.create_table('match_events',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('GOAL', 'OWN_GOAL', 'YELLOW_CARD', 'RED_CARD', 'SUBSTITUTION', 'PENALTY_SCORED', 'PENALTY_MISSED', 'HALF_TIME', 'FULL_TIME', 'POINT', 'NOTE', name='matcheventtype', native_enum=False), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('participant_id', sa.Uuid(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_match_events_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_match_events_fixture_id_fixtures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_match_events_participant_id_participants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_events_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_events'))
    )
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_match_events_fixture_created', ['fixture_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_events_fixture_id'), ['fixture_id'], unique=False)

    op.create_table('match_periods',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_match_periods_fixture_id_fixtures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_periods'))
    )
    with op.batch_alter_table('match_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_periods_fixture_id'), ['fixture_id'], unique=False)

    op.create_table('race_heats',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_race_heats_fixture_id_fixtures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_heats'))
    )
    with op.batch_alter_table('race_heats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_heats_fixture_id'), ['fixture_id'], unique=False)

    op.create_table('set_scores',
    sa.Column('fixture_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('home_points', sa.Integer(), nullable=False),
    sa.Column('away_points', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], name=op.f('fk_set_scores_fixture_id_fixtures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_scores'))
    )
    with op.batch_alter_table('set_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_scores_fixture_id'), ['fixture_id'], unique=False)

    op.create_table('standing_rows',
    sa.Column('standing_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['standing_id'], ['standings.id'], name=op.f('fk_standing_rows_standing_id_standings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_standing_rows_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standing_rows'))
    )
    with op.batch_alter_table('standing_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standing_rows_standing_id'), ['standing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_standing_rows_team_id'), ['team_id'], unique=False)

    op.create_table('race_entries',
    sa.Column('heat_id', sa.Uuid(), nullable=False),
    sa.Column('participant_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['heat_id'], ['race_heats.id'], name=op.f('fk_race_entries_heat_id_race_heats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_race_entries_participant_id_participants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_race_entries_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_entries'))
    )
    with op.batch_alter_table('race_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_entries_heat_id'), ['heat_id'], unique=False)

    op.create_table('race_results',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('time_seconds', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('FINISHED', 'DNS', 'DNF', 'DQ', name='raceoutcome', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['race_entries.id'], name=op.f('fk_race_results_entry_id_race_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_results'))
    )
    with op.batch_alter_table('race_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_results_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_results_entry_id'))

    op.drop_table('race_results')
    with op.batch_alter_table('race_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_entries_heat_id'))

    op.drop_table('race_entries')
    with op.batch_alter_table('standing_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standing_rows_team_id'))
        batch_op.drop_index(batch_op.f('ix_standing_rows_standing_id'))

    op.drop_table('standing_rows')
    with op.batch_alter_table('set_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_scores_fixture_id'))

    op.drop_table('set_scores')
    with op.batch_alter_table('race_heats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_heats_fixture_id'))

    op.drop_table('race_heats')
    with op.batch_alter_table('match_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_periods_fixture_id'))

    op.drop_table('match_periods')
    with op.batch_alter_table('match_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_events_fixture_id'))
        batch_op.drop_index('ix_match_events_fixture_created')
        batch_op.drop_index(batch_op.f('ix_match_events_created_at'))

    op.drop_table('match_events')
    with op.batch_alter_table('live_match_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_match_states_fixture_id'))

    op.drop_table('live_match_states')
    with op.batch_alter_table('fixture_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixture_participants_fixture_id'))

    op.drop_table('fixture_participants')
    with op.batch_alter_table('bracket_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bracket_nodes_bracket_id'))

    op.drop_table('bracket_nodes')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_published_at'))
        batch_op.drop_index('ix_announcements_published')

    op.drop_table('announcements')
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standings_sport_id'))

    op.drop_table('standings')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))

    op.drop_table('group_members')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_status'))
        batch_op.drop_index('ix_fixtures_start_status')
        batch_op.drop_index('ix_fixtures_sport_status')
        batch_op.drop_index(batch_op.f('ix_fixtures_sport_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_score_official_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_scheduled_start'))
        batch_op.drop_index(batch_op.f('ix_fixtures_published'))

    op.drop_table('fixtures')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_participant_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_sport_id'))

    op.drop_table('groups')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_teams_sport_id'))
        batch_op.drop_index(batch_op.f('ix_teams_department_id'))

    op.drop_table('teams')
    op.drop_table('sport_rules')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_participants_department_id'))

    op.drop_table('participants')
    with op.batch_alter_table('medals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medals_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_medals_department_id'))

    op.drop_table('medals')
    with op.batch_alter_table('department_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_points_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_department_points_department_id'))

    op.drop_table('department_points')
    with op.batch_alter_table('competition_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competition_stages_sport_id'))

    op.drop_table('competition_stages')
    with op.batch_alter_table('brackets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brackets_sport_id'))

    op.drop_table('brackets')
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_tournament_id'))

    op.drop_table('venues')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    op.drop_table('uploaded_files')
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sports_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_sports_slug'))
        batch_op.drop_index(batch_op.f('ix_sports_display_order'))

    op.drop_table('sports')
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sponsors_tournament_id'))

    op.drop_table('sponsors')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_target_id'))
        batch_op.drop_index(batch_op.f('ix_notification_preferences_subscription_id'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_event_id'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_departments_slug'))
        batch_op.drop_index(batch_op.f('ix_departments_abbreviation'))

    op.drop_table('departments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_is_current'))

    op.drop_table('tournaments')
    op.drop_table('roles')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_is_active'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_templates_key'))

    op.drop_table('notification_templates')
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_events_target_id'))
        batch_op.drop_index(batch_op.f('ix_notification_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_notification_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_notification_events_created_at'))
        batch_op.drop_index('ix_notification_events_created')

    op.drop_table('notification_events')
    # ### end Alembic commands ###
